### ISSUE TITLE
What happened to Bash Test Tools?

### ISSUE THREAD

**Issue by timoc** [videntifier/hackathon#1]
Hi,

I've been looking into test frameworks for bash, and came across this:
https://videntifier.github.io/bash_test_tools/

It looks great, any chance you can re-release it?

**Comment by thorsteinssonh** [comment]
Dear Timoc, apologies for this.
The project has now been transfered to my personal github account.
Try cloning from here:   https://github.com/thorsteinssonh/bash_test_tools.git
The old path should also redirect to this new home. I'll update the docs to reflect this.
If you like it or have ideas please feel free to join.
